### ISSUE TITLE
Unnecessary inconsistencies between LURE and PKGBUILD formats

### ISSUE THREAD

**Issue by BrodieRobertson** [Arsen6331/lure#15]
I see that the LURE script format is intended to be very similar to that of the AUR PKGBUILD, but why the change in variable names

LURE uses variables like: name, version, release, desc, homepage, architectures, deps
The AUR equivalents being: pkgname, pkgver, pkgrel, pkgdesc, url, arch, depends

I know you've mentioned wanting to at some point make a tool to convert AUR PKGBUILDs into LURE scripts so wouldn't it be simpler to reduce the inconsistencies where they offer no value.

**Comment by Arsen6331** [comment]
The inconsistencies are there because I believe them to be better names for the variables. Since AUR pacakges, even if converted, will never be usable out of the box due to the fact that different distros have different conventions, I thought that I might as well change the variable names, since packagers will have to intervene regardless.

One of the reasons PKGBUILDs use the names that they do is because `makepkg`, the tool that executes them, is written in bash, and has its own variables, that would conflict with those in the script. LURE, since it's written in Go and uses a pure-Go implementation of bash, doesn't have such constraints, so I can take a bit more liberty with the names.

**Comment by Arsen6331** [comment]
To be clear, the conversion tool will be extremely simple. They are both bash scripts, after all, and they have very similar variables/functions.

**Comment by venomdev** [comment]
I do like the new names, they do seem more intuitive. Would it be difficult to add aliases inside the tool so that AUR scripts can be read natively? If the format of each section is the same then the functions should work and a conversion tool wouln't be necessary for AUR packages at least.

**Comment by SinTan1729** [comment]
The only gripe I have with the variable names is that one has to access the current architecture using the variable `$architectures`, which just feels wrong. It should definitely be singular.

**Comment by Arsen6331** [comment]
> The only gripe I have with the variable names is that one has to access the current architecture using the variable `$architectures`, which just feels wrong. It should definitely be singular.

That is not the case. The `architectures` is an array of all the architectures supported by the package. To access the current architecture, you'd use `$ARCH`, which I've just realized I forgot to document, I'm going to need to do that.

**Comment by SinTan1729** [comment]
> That is not the case.

You're right. `$ARCH` is the way to go. Although, there is probably some bug, because the `$architectures` variable always returns the first architecture in the list. That is why it was still working even though $ARCH` is the proper variable.

**Comment by Arsen6331** [comment]
@SinTan1729 The documentation for the variables has been added (#41)
