### ISSUE TITLE
Port request

### ISSUE THREAD

**Issue by pkking** [Arsen6331/lure#21]
Hi there, im a [openeuler developer](https://www.openeuler.org/), this project is a good idea, and we want to port it into openeuler community, do you think it's a good time to do this? I'm glad to do some sorts of the port working :)

**Comment by Arsen6331** [comment]
Hello. I don't think now would be the right time to port LURE, because I don't believe it is ready for end users yet. Since there are not many packages and not many users, I have not had enough time to find and fix all the bugs yet, or to improve the user experience using feedback. If you have a testing repo, it might fit there. Otherwise, I think waiting until I release version 1.0.0 would be a good idea. Thank you.
