### ISSUE TITLE
Can't get git sources

### ISSUE THREAD

**Issue by Elagoht** [Arsen6331/lure#22]
I can't get git sources by typing `git+repoaddress`. Tested on Fedora, Debian and Arch Linux in same day. 

I always get this output:

```
goroutine 1 [running]:
main.getSources({0xd9aa90, 0xc0001d8e00}, {0xc00003a0f0, 0x2d}, 0xc0002ba000)
        /home/appveyor/projects/lure/build.go:445 +0x29e
main.buildPackage({0xd9aa90, 0xc0001d8e00}, {0xc6d837, 0x7}, {0xd9ec20, 0x1338a90})
        /home/appveyor/projects/lure/build.go:216 +0x978
main.buildCmd(0xc0001d9100)
        /home/appveyor/projects/lure/build.go:94 +0xe5
github.com/urfave/cli/v2.(*Command).Run(0xc000290120, 0xc0001d8f80)
        /home/appveyor/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/urfave/cli/v2@v
2.16.3/command.go:173 +0x6ca
github.com/urfave/cli/v2.(*App).RunContext(0xc0001628c0, {0xd9aa90?, 0xc0001d8e00},
{0xc000136000, 0x2, 0x2})
        /home/appveyor/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/urfave/cli/v2@v
2.16.3/app.go:383 +0xfde
main.main()
        /home/appveyor/projects/lure/main.go:134 +0xd25
```

**Comment by Arsen6331** [comment]
I'm assuming you're using v0.0.2. If so, you are getting a panic at https://github.com/Arsen6331/lure/blob/v0.0.2/build.go#L445. This doesn't make sense to me as that line would only panic if `bv.Checksums` was `nil`, and it can't be nil because L434 checks to see if their lengths are equal, and if they were both `nil`, the loop would never run, so that code should've never executed.

Before the stack trace, there should be an error message starting with `panic:`. Can you send that too? That may give me a clue as to what's going on.

**Comment by Elagoht** [comment]
Hmm. Reading source code enlightened me. Sorry I just missed type:

```
checksums="SKIP"
```
