### ISSUE TITLE
[Idea] Multiple files for other distro changes

### ISSUE THREAD

**Issue by ErikReider** [Arsen6331/lure#34]
Here's a idea that might make maintaining a lure pkg a bit easier. 

So we keep the lure.sh script but we add more scripts like "fedora.sh" which contains overrides for deps, build, package, etc but without all of the main variables like version and name. So keep "build_deps" and "deps" and move the "fedora-deps" into its own file.

This would eliminate the need for 10+ lines of different distro specific changes.

**Comment by Cerberus1746** [comment]
Yeah, personally I prefer to have multiple files separated on their on rather than a massive text file, they tend to be messy. Annoying to maintain too because if more than one person makes a pull request on the package it will be extremely annoying to merge and having a lot of files avoid that a LOT.

Imagine how many people would want to update python, for example, when a new version comes out...

You could also have a separate file for a master prepare action too if it's the same for all.

**Comment by Cerberus1746** [comment]
> This should already be possible using `source`. I'll probably just need to add a variable for the directory with the scripts.

Like, having a folder named "source" and then having a filename with the distro in it?

or a folder with the distro name and then files named source and etc?

**Comment by Cerberus1746** [comment]
Yeah, that also works :-P

**Comment by Arsen6331** [comment]
With the addition of the cache database, this is going to take some work since the DB also needs to be updated when the extra scripts are changed, and it's currently intentionally restricted from executing any commands or reading any files while interpreting a script for storage in the DB, so that will need to be changed and restricted to only allow the `source` command and files within the same directory as the script.

**Comment by Arsen6331** [comment]
This has now been implemented in 3c260a7c5fc5048dcdb8a832ab09b48845458e90. Simply do `source $scriptdir/fedora.sh`, or whatever the name is in `lure.sh`, and in the script you `source`, put variables and functions with overrides, like `deps_fedora` and `package_fedora() {  }`.

**Comment by Arsen6331** [comment]
I will create and upload examples soon
