### ISSUE TITLE
Lure tries to put a dependency that is not in the list of required

### ISSUE THREAD

**Issue by xpamych** [Arsen6331/lure#54]
when I try to run to check the health of the [script I am writing](https://gitflic.ru/project/xpamych/xpamych-lure-repo/blob?file=qt6-git%2Flure.sh) , lure tries to install espanso-bin, although it is not in the list of required dependencies.
![image](https://user-images.githubusercontent.com/16473797/209943669-d104ccfa-636f-4c18-9980-7a110c3c3c55.png)

**Comment by Arsen6331** [comment]
Ok, this is an interesting one.

In your script, you have `build_deps=('')`

If you look at [`espanso-bin`](https://lure.arsenm.dev/pkg/default/espanso-bin), you can see that it has a `provides` variable, but it's empty for some reason. If you then view the script, you'll see it's because it has `provides=("${pkgname%-bin}")`. It uses `pkgname` instead of `name`, so bash resolves it to an empty string.

So when you try to install, LURE takes that empty string and tries to look for it in the DB, and it gets back `espanso-bin` because it provides `''`

**Comment by Arsen6331** [comment]
I'll fix this by adding a special case and returning nothing if the name is empty.

**Comment by xpamych** [comment]
oh, this is unexpected)

**Comment by Arsen6331** [comment]
This should be fixed in 55132437b3c2d9bff6ae317a9f6e82d686afa349, can you test it?

**Comment by Arsen6331** [comment]
I'll close this because it's been fixed in my testing, but if you still have this problem, please reopen or create a new issue. Thanks.
