### ISSUE TITLE
How to add repo?

### ISSUE THREAD

**Issue by fethomm** [Arsen6331/lure#57]
Writing an article on LURE, I ran into a little problem. Trying to build Espanso from the default repo in Debian or Ubuntu did not succeed, while it did build on Fedora 37. So I tried to add the repo for Espanso. The command I used was `lure ar -n esp -u https://github.com/espanso/espanso.git`  That tells me, that 'esp' is not a valid repo. I know this software is in an early stage, but could you please elaborate a bit on adding repos (and maybe add that to the documentation). That might bring in new testers as well. Thanks for this promising tool!

**Comment by Arsen6331** [comment]
You already have the repo for it installed, as it's in the default repo. The reason you're getting an error is that the build script for it is invalid. If you look at https://github.com/Arsen6331/lure-repo/blob/6114e20fe08eeb565b858076adca0a26dd2418c6/espanso-bin/lure.sh#L8, you can see that it's using `pkgname` instead of the `name` variable. I'll fix that in a moment and then you should be good.

**Comment by Arsen6331** [comment]
I just fixed it, the package should be working now. In fact, since the provides array is now valid, you can just do `lure in espanso` instead of having to use the `-bin` suffix. If it works, I'll close this issue. Thanks.

**Comment by fethomm** [comment]
It works, thanks.

**Comment by Arsen6331** [comment]
Great, closing this issue then.

**Comment by Arsen6331** [comment]
Also, just to clarify, you weren't getting an error on Fedora because RPM is fine with an empty package name in provides, whereas Debian's Dpkg considers that invalid and refuses to install. I'll have to make a PR to nFPM to have it return a proper error message in that case, thanks for bringing this to my attention.
