### ISSUE TITLE
How to uninstall? Where do the application files go?

### ISSUE THREAD

**Issue by darkk99** [Arsen6331/lure#58]
Running OpenSUSE, and I happened to be dual-package managing with DNF. It detected DNF, so i removed DNF (had no use for it) and then it detected zypper. I had removed the binary from my system, however it refuses to reinstall, saying it has already been installed. I need to delete the application files, where are they? Already deleted `/usr/bin/lure`

**Comment by Arsen6331** [comment]
I'm assuming you mean that zypper refused to reinstall? The reason is that DNF and Zypper both install via RPM behind the scenes, so it was actually still installed on your system and you just need to remove the package. I'm assuming you've figured that out since you closed the issue, but I'll still put this here for other people to see if they encounter this issue.

However, you actually don't need to reinstall because if you removed DNF, LURE will automatically use Zypper when you run it next.
